### GIT
alias glg='git log --graph --pretty=oneline --abbrev-commit --decorate --all'
alias gl='git log'
alias gd='git diff'
alias gba='git branch -a'
alias gs='git status'
alias ga='git add'
alias gaa='git add --all'
alias gc='git commit'
alias gca='git commit -a'
alias gm='git merge'
alias gco='git checkout'
alias gce='git config --global e'
